Remove JNI macos directory
Currently, macOS is not supported. Having this directory here breaks builds on apps that import jni and build macOS (among other platforms), even though if they don't need jni/jnigen for macOS specifically (and only use it on Android, for example).

Therefore, removing this directory should fix the issue for now before macOS support is actually added to the package.

```
macos/Classes/jni.c:3:10: fatal error: '../../src/jni.c' file not found
#include "../../src/jni.c"
         ^~~~~~~~~~~~~~~~~
```